version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: react-responsive-carousel
    versions:
    - 3.2.11
    - 3.2.12
    - 3.2.13
    - 3.2.14
    - 3.2.15
    - 3.2.16
  - dependency-name: moize
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
